---
title: "Toccatr Package development"
author: "James Smith, Talisman Therapeutics" 
output: 
  html_document: 
    df_print: paged 
    code_folding: hide 
    code_download: true 
date: Wed 26 Mar 2025
---



### Intro

**Tali**sman **H**elp for **O**pera formerly Tallyho, now Toccatr\
A few other packages exist named Tallyho, so this was renamed to toccatr (from **Toccata**: noun, *a musical form for keyboard instruments*, *written in a free style that is characterized by full chords*, *rapid runs and high* [harmonies](https://www.revvity.com/hk-en/product/harmony-5-2-office-revvity-hh17000019))

```{r setup, warning=FALSE, message=FALSE}
library(devtools)
library(roxygen2)

library(tidyverse, quietly = TRUE) 
library(janitor, quietly = TRUE) 
library(plotly, quietly = TRUE)

# If this is the first time running toccatr, the following is needed to install it
# install.packages("devtools")
# library(devtools)
# install_github("jsmithss/toccatr")


```

### To do

-   Need to add prismy and plate centering to functions and remove generic ones

-   Auto=filtering for platemap function so that there is only one plate: 

`first_plate <- df[1, platename] # Get the platename of the first row`
`filtered_df <- df %>% dplyr::filter(platename == first_plate) # Select rows with the same plate`

-   Adapt platemap and heatmap so they will take 384 as well as 96. Suggest adding qualifier in function parameters  

-   Change requirements to individual packages rather than "tidyverse"  

-   Make harm_check function which runs through identical import but returns the output as a table of each data file imported with platename, eval name, number of variables and number of obs  

-   Explicitly call functions from other packages e.g. dplyr::bind_rows  

-   Fix popup help for ploxy function  

-   Add a [custom dataset](https://www.r-bloggers.com/2024/10/beyond-functions-how-to-enrich-an-r-package-with-data/) with compounds and likely data, also a timecourse  



